const markets = [
  'Vietnam',
  'Thailand',
  'Malaysia',
  'Indonesia',
  'Singapore',
  'Southeast Asia',
  'United States',
  'Europe',
];

const localizedPage = ({
  path,
  owner,
  primaryKeyword,
  cnPrimaryKeyword,
  secondaryKeywords,
  cnSecondaryKeywords = [],
  geoTargets = markets.slice(0, 4),
}) => [
  {
    url: `https://www.pintecl.com/en/${path}`,
    owner,
    primaryKeyword,
    secondaryKeywords,
    geoTargets,
  },
  {
    url: `https://www.pintecl.com/cn/${path}`,
    owner,
    primaryKeyword: cnPrimaryKeyword || primaryKeyword,
    secondaryKeywords: cnSecondaryKeywords.length ? cnSecondaryKeywords : secondaryKeywords,
    geoTargets,
  },
];

const productCategories = [
  ['PK', 'rough surface hot stamping foil', '粗面烫金箔', ['PK brown back foil', 'rough paper stamping foil', 'embossed leather stamping foil'], ['PK咖啡底烫金箔', '粗纹纸烫金箔', '压纹皮革烫金箔'], ['Vietnam', 'Southeast Asia']],
  ['PC', 'plastic hot stamping foil', '塑胶烫金箔', ['cosmetic packaging foil', 'cold foil for plastic', 'alcohol resistant foil'], ['化妆品包装烫金箔', '塑料冷烫箔', '耐酒精烫金箔'], ['Vietnam', 'Thailand', 'Malaysia']],
  ['PLPY', 'pigment foil', '颜料箔', ['PL PY pigment foil', 'opaque color foil', 'matte pigment foil'], ['PLPY颜料箔', '不透底色箔', '哑面颜料箔'], ['Vietnam', 'Thailand', 'Malaysia', 'Indonesia']],
  ['DIGITAL', 'digital cold foil', '数码冷烫箔', ['plate-free foil stamping', 'short-run packaging foil', 'MGI compatible foil'], ['免制版烫金', '短单包装烫金箔', 'MGI兼容冷烫箔'], ['Southeast Asia', 'Europe', 'United States']],
  ['GLITTER', 'premium glitter powder', '金葱粉', ['solvent resistant glitter', 'cosmetic glitter powder', 'PET glitter'], ['耐溶剂金葱粉', '化妆品级金葱粉', 'PET金葱粉'], ['United States', 'Europe', 'Southeast Asia']],
];

const productItems = [
  ['PK-Universal', 'PK universal foil', 'PK通用型烫金箔', ['PK brown back universal foil', 'general packaging hot stamping foil'], ['PK咖啡底通用箔', '通用包装烫金箔']],
  ['PK-Heavy', 'PK heavy duty foil', 'PK强力型烫金箔', ['anti-oxidation foil', 'heavy ink hot stamping foil'], ['抗氧化烫金箔', '重油墨烫金箔']],
  ['PK-Matte', 'PK matte foil', 'PK哑面烫金箔', ['matte metallic foil', 'anti-fingerprint matte foil'], ['哑面金属箔', '抗指纹哑面烫金箔']],
  ['PK-Holo', 'PK holographic plain foil', 'PK全息素面烫金箔', ['security holographic foil', 'rainbow holographic foil'], ['防伪全息烫金箔', '彩虹全息箔']],
  ['PC-Standard', 'PC standard plastic foil', 'PC标准塑胶烫金箔', ['ABS stamping foil', 'plastic surface foil'], ['ABS烫金箔', '塑胶表面烫金箔']],
  ['PC-Alcohol', 'PC alcohol resistant foil', 'PC耐酒精烫金箔', ['cosmetic grade foil', 'perfume packaging foil'], ['化妆品级烫金箔', '香水包装烫金箔']],
  ['PC-Cold', 'PC cold foil', 'PC冷烫箔', ['UV cold foil', 'digital cold foil for plastic'], ['UV冷烫箔', '塑胶数码冷烫箔']],
  ['PL-Glossy', 'PL glossy pigment foil', 'PL亮面颜料箔', ['glossy color foil', 'opaque pigment foil'], ['亮面彩色箔', '不透底颜料箔']],
  ['PY-Matte', 'PY matte pigment foil', 'PY哑面颜料箔', ['matte color foil', 'pigment foil for gift packaging'], ['哑面彩色箔', '礼品包装颜料箔']],
  ['PL-White', 'white pigment foil', '白色颜料箔', ['opaque white foil', 'white stamping foil'], ['高遮盖白色箔', '白色烫金箔']],
  ['G-Hex', 'hexagonal glitter powder', '六角金葱粉', ['PET glitter powder', 'solvent resistant glitter'], ['PET金葱粉', '耐溶剂金葱粉']],
  ['G-Strip', 'strip glitter powder', '长条金葱粉', ['strip cut glitter', 'decorative glitter powder'], ['长条闪粉', '装饰金葱粉']],
];

const solutions = [
  ['pkg_bags', 'hot stamping foil for packaging bags', '包装袋烫金箔', ['fold resistant foil', 'bag crease stamping foil'], ['耐折包装烫金箔', '袋子折线烫金箔']],
  ['special_paper', 'hot stamping foil for specialty paper', '特种纸烫金箔', ['rough paper foil', 'textured paper stamping foil'], ['粗纹纸烫金箔', '纹理纸烫金箔']],
  ['leather', 'hot stamping foil for leather', '皮革烫金箔', ['PU leather foil', 'PVC leather stamping foil'], ['PU皮革烫金箔', 'PVC皮革烫金箔']],
  ['plastic_surface', 'hot stamping foil for plastic surfaces', '塑胶表面烫金箔', ['injection plastic foil', 'cross-cut test foil'], ['注塑件烫金箔', '百格测试烫金箔']],
  ['digital_cold', 'digital cold foil solution', '数码冷烫解决方案', ['MGI cold foil', 'Scodix compatible foil'], ['MGI冷烫箔', 'Scodix兼容冷烫箔']],
  ['bottles', 'hot stamping foil for bottles', '瓶盖瓶身烫金箔', ['glass bottle foil', 'deep draw cap foil'], ['玻璃瓶烫金箔', '瓶盖深拉伸烫金箔']],
  ['gift_pkg', 'hot stamping foil for gift packaging', '礼品包装烫金箔', ['gift box pigment foil', 'greeting card foil'], ['礼盒颜料箔', '贺卡烫金箔']],
  ['reverse_uv', 'hot stamping foil for reverse UV varnish', '逆向UV烫金箔', ['tactile varnish foil', 'UV adhesion foil'], ['触感UV烫金箔', 'UV附着烫金箔']],
];

const pages = [
  ...localizedPage({
    path: '',
    owner: 'Homepage',
    primaryKeyword: 'hot stamping foil manufacturer',
    cnPrimaryKeyword: '烫金箔厂家',
    secondaryKeywords: ['cold foil supplier', 'holographic foil manufacturer', 'China hot stamping foil exporter'],
    cnSecondaryKeywords: ['冷烫箔供应商', '全息烫金箔厂家', '中国烫金膜出口商'],
    geoTargets: ['Vietnam', 'Thailand', 'Malaysia', 'Indonesia', 'Southeast Asia'],
  }),
  ...localizedPage({
    path: 'products/',
    owner: 'Product Catalog',
    primaryKeyword: 'hot stamping foil manufacturer',
    cnPrimaryKeyword: '烫金箔产品目录',
    secondaryKeywords: ['cold foil', 'holographic foil', 'digital cold foil'],
    cnSecondaryKeywords: ['冷烫箔', '全息烫金箔', '数码冷烫箔'],
    geoTargets: ['Vietnam', 'Thailand', 'Malaysia', 'Indonesia', 'Southeast Asia'],
  }),
  ...localizedPage({
    path: 'products/foils/',
    owner: 'Foil Color Range',
    primaryKeyword: 'hot stamping foil color range',
    cnPrimaryKeyword: '烫金箔色卡',
    secondaryKeywords: ['foil color swatches', 'metallic foil colors', 'custom foil colors'],
    cnSecondaryKeywords: ['烫金膜色卡', '金属箔颜色', '定制烫金箔颜色'],
  }),
  ...localizedPage({
    path: 'quote/',
    owner: 'Sales Inquiry',
    primaryKeyword: 'hot stamping foil supplier inquiry',
    cnPrimaryKeyword: '烫金箔在线报价',
    secondaryKeywords: ['custom hot stamping foil quote', 'cold foil wholesale inquiry', 'foil sample request'],
    cnSecondaryKeywords: ['定制烫金箔报价', '冷烫箔批发询价', '烫金箔样品申请'],
    geoTargets: ['Vietnam', 'Thailand', 'Malaysia', 'Indonesia', 'Southeast Asia'],
  }),
  ...localizedPage({
    path: 'about/',
    owner: 'Company Profile',
    primaryKeyword: 'Dongguan hot stamping foil manufacturer',
    cnPrimaryKeyword: '东莞烫金箔厂家',
    secondaryKeywords: ['PINTE hot stamping foil factory', 'BEST Craftwork foil manufacturer'],
    cnSecondaryKeywords: ['PINTE品特烫金箔工厂', '佰仕特烫金箔厂家'],
    geoTargets: ['Vietnam', 'Southeast Asia', 'United States', 'Europe'],
  }),
  ...localizedPage({
    path: 'tour/',
    owner: 'Factory Proof',
    primaryKeyword: 'hot stamping foil factory tour',
    cnPrimaryKeyword: '烫金箔工厂参观',
    secondaryKeywords: ['foil coating factory', 'hot stamping foil production line'],
    cnSecondaryKeywords: ['烫金膜涂布工厂', '烫金箔生产线'],
  }),
  ...localizedPage({
    path: 'blog/',
    owner: 'Content Hub',
    primaryKeyword: 'hot stamping foil guide',
    cnPrimaryKeyword: '烫金箔知识指南',
    secondaryKeywords: ['foil stamping knowledge', 'packaging foil articles'],
    cnSecondaryKeywords: ['烫金膜知识', '包装烫金文章'],
  }),
  ...productCategories.flatMap(([id, primaryKeyword, cnPrimaryKeyword, secondaryKeywords, cnSecondaryKeywords, geoTargets]) => localizedPage({
    path: `products/category/${id}/`,
    owner: 'Product Series',
    primaryKeyword,
    cnPrimaryKeyword,
    secondaryKeywords,
    cnSecondaryKeywords,
    geoTargets,
  })),
  ...productItems.flatMap(([id, primaryKeyword, cnPrimaryKeyword, secondaryKeywords, cnSecondaryKeywords]) => localizedPage({
    path: `products/item/${id}/`,
    owner: 'Product Item',
    primaryKeyword,
    cnPrimaryKeyword,
    secondaryKeywords,
    cnSecondaryKeywords,
  })),
  ...solutions.flatMap(([id, primaryKeyword, cnPrimaryKeyword, secondaryKeywords, cnSecondaryKeywords]) => localizedPage({
    path: `solutions/${id}/`,
    owner: 'Application Solution',
    primaryKeyword,
    cnPrimaryKeyword,
    secondaryKeywords,
    cnSecondaryKeywords,
  })),
];

export default {
  brand: 'PINTE',
  defaultLocale: 'en',
  markets,
  productKeywords: [
    'hot stamping foil',
    'cold foil',
    'digital cold foil',
    'holographic foil',
    'pigment foil',
    'metallic foil',
    'hot stamping foil manufacturer',
    'hot stamping foil supplier',
    'China hot stamping foil exporter',
  ],
  geoKeywords: [
    'Vietnam hot stamping foil supplier',
    'Thailand hot stamping foil supplier',
    'Malaysia hot stamping foil supplier',
    'Indonesia hot stamping foil supplier',
    'Southeast Asia hot stamping foil manufacturer',
    'hot stamping foil supplier Vietnam',
    'custom hot stamping foil Southeast Asia',
  ],
  pages,
};
